### PR TITLE
Adds a new `WithDriver` option, to enable modified or alternate drivers

### PR DESCRIPTION
**Pull request by pbedat**
Hi!

I'm using sqlite3 extensions like this:

```go
sql.Register("sqlite3-ext", &sqlite3.SQLiteDriver{
	Extensions: []string{
		path.Join(lang.Must(os.Getwd()), "../.sqlpkg/nalgeon/regexp/regexp.so"),
	},
})
```

the driver name is hard coded in comfylite3, so I think this could be a reasonable addition. 

What do you think?

### CODE REVIEW

**Comment by davidroman0O** [comment]
Oh nice, yea a lot of small improvements should be done to allow those things, thank you for the pull request, i will test it tomorrow and come back to you :)

**Comment by davidroman0O** [comment]
Oh I see, very simple and very reasonable addition indeed! I should have validated yesterday :p

**Comment by davidroman0O** [comment]
Thank you a lot! :)

**Comment by pbedat** [comment]
my pleasure :)

**Pull request merged**
